// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXa4BkBDplHMbSkiIH4d8l2vrf2oXL9vM',
    appId: '1:362857030405:web:c5b7750a5d98f921118d6c',
    messagingSenderId: '362857030405',
    projectId: 'kafelo-mobile-application',
    authDomain: 'kafelo-mobile-application.firebaseapp.com',
    storageBucket: 'kafelo-mobile-application.firebasestorage.app',
    measurementId: 'G-C2L98KHGJ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhqRACe9-Pfsr833sCVCe7pLuf5GPLHAc',
    appId: '1:362857030405:android:40c3786c4a9349ba118d6c',
    messagingSenderId: '362857030405',
    projectId: 'kafelo-mobile-application',
    storageBucket: 'kafelo-mobile-application.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoFlJaXFZYiU3U-gX1ejwcCEDxm7OzzCc',
    appId: '1:362857030405:ios:1ce4b7642833634a118d6c',
    messagingSenderId: '362857030405',
    projectId: 'kafelo-mobile-application',
    storageBucket: 'kafelo-mobile-application.firebasestorage.app',
    iosBundleId: 'com.example.localBasedCoffeeShopsMobileApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoFlJaXFZYiU3U-gX1ejwcCEDxm7OzzCc',
    appId: '1:362857030405:ios:1ce4b7642833634a118d6c',
    messagingSenderId: '362857030405',
    projectId: 'kafelo-mobile-application',
    storageBucket: 'kafelo-mobile-application.firebasestorage.app',
    iosBundleId: 'com.example.localBasedCoffeeShopsMobileApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXa4BkBDplHMbSkiIH4d8l2vrf2oXL9vM',
    appId: '1:362857030405:web:a39a5f61afee3319118d6c',
    messagingSenderId: '362857030405',
    projectId: 'kafelo-mobile-application',
    authDomain: 'kafelo-mobile-application.firebaseapp.com',
    storageBucket: 'kafelo-mobile-application.firebasestorage.app',
    measurementId: 'G-FPWHJB0E1N',
  );
}
